# Generated by Django 3.2.6 on 2021-09-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
